# Generated by Django 3.0.4 on 2020-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymetrics',
            name='face_photo',
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='face_recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dailymetrics',
            name='chest_recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
