# Generated by Django 3.0.5 on 2020-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200322_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_on', models.DateTimeField(auto_now_add=True)),
                ('app_heart_rate', models.DecimalField(decimal_places=3, max_digits=3)),
                ('device_heart_rate', models.DecimalField(decimal_places=3, max_digits=3)),
                ('app_saturation', models.DecimalField(decimal_places=3, max_digits=3)),
                ('device_saturation', models.DecimalField(decimal_places=3, max_digits=3)),
                ('device_type', models.TextField()),
                ('measurement_method', models.TextField(choices=[('a', 'a'), ('b', 'b')])),
                ('lightning', models.TextField(choices=[('dark room', 'dark room'), ('natural', 'natural'), ('lamp', 'lamp')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('past_medical_status', models.TextField(blank=True, null=True)),
                ('face_recording', models.FileField(blank=True, null=True, upload_to='')),
                ('chest_recording', models.FileField(blank=True, null=True, upload_to='')),
                ('finger_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
