# Generated by Django 3.0.5 on 2020-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anonymousmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='app_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='app_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='device_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='device_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='device_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='measurement_method',
            field=models.TextField(choices=[('PHONE_ON_THE_MEASURING_HAND', 'phone on the measuring hand'), ('PHONE_ON_THE_OTHER_HAND', 'phone on the other hand'), ('PHONE_ON_TABLE', 'phone on the table')]),
        ),
    ]
