# Generated by Django 3.0.4 on 2020-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200406_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousmetrics',
            name='heart_rate_diff',
        ),
        migrations.RemoveField(
            model_name='anonymousmetrics',
            name='saturation_diff',
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='lightning',
            field=models.TextField(choices=[('DARK_ROOM', 'DARK_ROOM'), ('NATURAL', 'NATURAL'), ('LAMP', 'LAMP')]),
        ),
        migrations.AlterField(
            model_name='anonymousmetrics',
            name='measurement_method',
            field=models.TextField(choices=[('PHONE_ON_THE_MEASURING_HAND', 'PHONE_ON_THE_MEASURING_HAND'), ('PHONE_ON_THE_OTHER_HAND', 'PHONE_ON_THE_OTHER_HAND'), ('PHONE_ON_TABLE', 'PHONE_ON_TABLE')]),
        ),
    ]
