# Generated by Django 3.0.4 on 2020-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200413_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmetrics',
            name='position',
            field=models.TextField(blank=True, choices=[('SITTING', 'SITTING'), ('LAYING_DOWN', 'LAYING_DOWN'), ('STANDING', 'STANDING')], null=True),
        ),
    ]
