# Generated by Django 3.0.4 on 2020-04-24 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_anonymousmetrics_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('display_name', models.TextField()),
                ('qtype', models.CharField(choices=[('CHECKBOX', 'CHECKBOX'), ('TEXT', 'TEXT'), ('MULTISELECT', 'MULTISELECT'), ('SELECT', 'SELECT'), ('RANGER', 'RANGER')], max_length=25)),
                ('order', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='api.Question')),
            ],
        ),
        migrations.DeleteModel(
            name='AnonymousMetrics',
        ),
        migrations.DeleteModel(
            name='DailyMetrics',
        ),
    ]
