# Generated by Django 3.0.4 on 2020-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200424_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='display_name_he',
            field=models.TextField(null=True),
        ),
    ]
