# Generated by Django 3.0.4 on 2020-04-25 09:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200424_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_data_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='extra_data_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='')),
                ('recording_metadata', models.TextField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_voice_recordings', to='api.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.Measurement')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.Question')),
            ],
        ),
        migrations.CreateModel(
            name='PPGMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('blue', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('green', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('timepoint', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('phone_metadata', models.TextField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppg_measurements', to='api.Measurement')),
            ],
        ),
    ]
