# Generated by Django 3.0.4 on 2020-04-27 10:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200425_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppgmeasurement',
            name='phone_metadata',
        ),
        migrations.AddField(
            model_name='measurement',
            name='exposure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='general_feeling',
            field=models.CharField(choices=[('SAME', 'SAME'), ('BETTER', 'BETTER'), ('WORSE', 'WORSE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='negative_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='positive_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temp_measurement',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='calibration_transform1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='calibration_transform2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_color_transform1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_color_transform2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_forward_matrix1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_forward_matrix2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_lens_shading_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_max_analog_sensitivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_reference_illuminant1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_reference_illuminant2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_sensitivity_range_lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_sensitivity_range_upper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppgmeasurement',
            name='sensor_white_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='background_diseases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='smoking_status',
            field=models.CharField(choices=[('NEVER', 'NEVER'), ('STOPPED', 'STOPPED'), ('CURRENT', 'CURRENT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
        ),
    ]
